import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { Fragment } from "react";
import TimeTracker from "../components/TimeTracker";

const Home: NextPage = () => {
  function onSave(duration: number) {
    if (duration <= 0) return;

    // TODO: Save duration to database
    console.log({ duration });
  }

  return (
    <Fragment>
      <div className="mx-auto my-auto flex items-center justify-center h-screen flex-col space-y-5">
        <Head>
          <title>Homepage</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 className="font-poppins text-center text-6xl md:text-7xl text-green-500 font-semibold">
          Hello, World!
        </h1>

        <Link href="/hello" passHref>
          <a>Go to /hello</a>
        </Link>
      </div>
      <TimeTracker onSave={onSave} />
    </Fragment>
  );
};

export default Home;
